---
title: "Alumni"
output: html_document
---

# Overview

Some day you will be on this elite list. If you have moved on and aren't here, please email Rob to tell him! Please also update us as your current status changes. We love to receive updates on your career goals and accomplishments. Your success is our success!

# Student Tracker

| Name                | Degree           | Project           |  Years   | Post-lab experience |
|---------------------|------------------|-------------------|----------|-------------------------------------------------------------|
| $Undergraduate$ $Supervision$ |||||
| Leila Forsythe       | BSc (thesis)     | Lythrum herbarium | 2015-16  | 2016-? PhD with Ben Gilbert, U Toronto St. George Campus |
| Stephanie Barre      | SLC (Co-op)      | Lab Technician    | 2015-16  | ???? |
| Erika Gibbons        | SLC (Co-op)      | Lab Technician    | 2015-16  | ???? |
| Victoria Guba        | BSc (mentorship) | Tick ID           | 2016     | 2018 Concordia, MSc in Environmental Assessment |
| Jordana de Lima      | BSc (Co-mentorship) | Tick genome       | 2016-17  | 2018 Brasil to complete degree (Science without Borders) |
| Emily Bao            | BSc (work study) | baRcodes          | 2016-18  | Job: 2018 Scotiabank -- Operating Systems Team Member |
| Angela Wong          | BSc (thesis)     | eDNA experiment   | 2016-17  | ???? | 
| Derek McLean         | BSc (thesis)     | Arctic birch DNA  | 2016-17  | ???? |
| Weihang (Kathleen) Chen         | BSc (Co-mentorship)| Ticks + GM      | 2016-17  | ???? |
| Vanessa Sabourin     | SLC (Co-op)      | Lab Technician    | 2016-17  | ???? |
| Jessie Obeng         | BSc (work study) | Lab servers       | 2017-18  | Job: 2018 eSight -- Data Analyst |
| Rhett Andruko        | BSc (USRA)       | GM + maple @ QUBS | 2017 (summer) | 2018-? MSc, School of Forestry -- Alberta |
| Anneke Golemeic      | BSc (thesis)     | GM root colonization | 2017-2018 | 2018-? MSc with Risa Sargent, U Ottawa |
| Sierra Klueppel      | BSc (thesis)     | Lythrum FT + herbivory | 2017-2018 | ???? |
| Pallavi Gupta        | BSc (mentorship + thesis) | Tick LAMP + Betula genetics | 2017-19 | ???? |
| Ke Fang   | BSc (Mitacs intern) | Lab technician | 2018 (summer) | ???? |
| Kate Ding            | BSc (mentorship) | Tick microbiome   | 2018-19  | ???? |
| Claire Smith | BSc (USRA) | GRENE-Net + mentorship | 2018 (sumer) | ???? |
| Haley Richardson     | BSc (thesis)     | ???? | 2018-19|| 
| Jamie MacKay         | BSc (thesis)     | ???? | 2018-19|| 
| Joanna Strozak       | BSc (thesis)     | ???? | 2018-19|| 
| Meagan Antunes       | BSc (thesis)     | ???? | 2018-19|| 
| $Graduate$ $Supervision$ |||||
| Muzzamil (Muzz) Abdur-Razak | MSc (Co-)    | Lythrum herbivory          | 2016-18 | ???? |
| Katherine Duchesneau | MSc (Co-)    | GM Soil microbiome         | 2016-18 | ???? |
| Yihan Wu             | MSc          | Lythrum herbarium + GM GBS | 2016-18 | ???? |
| Eugene Sit           | MSc (Co-)    | Lythrum FT x herbivory     | 2016-18 | ???? |
| Richard Honor        | MSc          | GM Fungal interactions     | 2018-20 | ???? |
| $Other$ $Personnel$ |||||
| Almira Siew        | The Wonder Technician          | Just about everything     | 2018-19 | Job: 2019 - Lab technician, Octane Medical Group |

# Major Awards & Honours

  * USRA -- Rhett Andruko, Claire Smith
  * OGS -- Eugene Sit
  * Outstanding TA award -- Muzzamil (Muzz) Abdur-Razak
  * QUBS-BUGS award -- Weihang (Kathleen) Chen; Jamie Mackay

