---
title: "Colautti Lab Manifesto <br> Management"
output: html_document
---

# Mental Health

Mental health has an unfortunate stigma in western society. However, a good way to think about it is analogous to physical health. You can't maintain a healthy mind with discipline and deliberate mindfulness practices in the same way you can't train for a marathon by sitting on your couch and eating potato chips.

The following is not a substitute for proper mental health care and training. However, most science programs do not do a good job of introducing students to world philosophies and an understanding of the roots of true happiness. The following short guide provides a brief introduction to inspire further research into this important topic.

## Stoicism and the Subtle Art

The following is drawn from a group of Greek Philosophers known as the 
[Stoics](https://en.wikipedia.org/wiki/Stoicism), and a 2016 International
best-selling book by Mark Manson called *The Subtle Art of Not Giving a F\*CK*

## The World is Amazing

In all of Earth's 4 billion year history, there is arguably no better time to be alive than right now. Despite the very real challenges facing our modern civilization, you are better off today than any of your ancestors. If you doubt this statement, take a look at [the data](https://www.vox.com/2014/11/24/7272929/global-poverty-health-crime-literacy-good-news)


## Why do I feel so bad?

**The Oxford Paradox:** A common misconception among high-achieving students is that success leads to happiness and contentment in life. But what if it's the opposite? What if happiness leads to success?

If success is the key to happiness, then why are students at Oxford University among some of the least happy [in the UK](https://www.oxfordstudent.com/2017/03/20/75387)?

Imagine you are the top student in your High School, and you are the only student in your school of 2,000 to get accepted to Oxford on a fully-paid scholarship! Imagine how happy you would feel. Why? Part of this happiness is the sense of accomplishment you feel at having achieved something that none of your peers have managed to do. You are a big fish in a little pond.

Fast forward to your time at Oxford and now you are struggle to pass your classes, and you feel like everyone else in your cohort at Oxford is smarter than you. You feel unhappy because everyone seems to be doing so much better and you feel like a failure.

This is an anology for the modern world. But instead of successful Oxford students, you are constantly compared to images and videos on the internet of people who seem to be more sucessful, more beautiful, more relaxed than you.

**More generally:** The desire to improve your situation has a negative effect on your mental health, while the acceptance of a negative experience has a positive effect.

# Management

Whether you are working on an Honours thesis for your BSc or the next paper for your postdoc, you are a manager. Nobody in the lab is more responsible for your project then you are. It can be difficult to make the transition from student to leader, so here are some tips.

## Project Managment

Your thesis or independent study project is an opportunity to work on your project management skills. It can make a great line for your CV and you will impress an interviewer if you can explain how you oversaw a research project from initial conception to final submission (or, ideally, publication!)

Planning is key. Research what other people have done, try to imagine yourself going through the motions. What do you need to prepare? What are some things that could go wrong and how can you help avoid or mitigate those problems?

## Scheduling

Make 3 schedules:

  * Daily schedule, updated every day
  * Weekly schedule of meetings and activities
  * A semester-long schedule of key deadlines
  
First, add in your essential items (e.g. class time, teaching/TA responsibilities) and key deadlines.

Next, identify your long-term goals for the semester, based on your 5-year and 10-year plan. Break these large projects and long-term goals into shorter SMART goals: **Specific**, **Measurable**, **Attainable**, **Realistic** and **Time-Bound**. Then, add time to your schedule to achieve these goals. Anything without a firm deadline tends to get pushed back unless you dedicate time to it.

Finally, re-assess your schedule periodically. A schedule is not set in stone and needs to be updated in light of new developments, responsibilities, goals, etc.

Be sure to include key deadlines like:

  * Vanier Fellowship - early Oct
  * NSERC PhD - mid Oct
  * NSERC CGS-M – late Nov
  * OGS – late April
  * Tuition Refund (Oct 31 – full; Nov 30 – 50%; Dec 31 – 25%)
  * BGSC Checklist: Committee Meetings, Research Proposal, Research Project Goals (e.g. data collection, analysis, writing)


## BACKUP

Backup is 100% essential. All the time and money that goes into collecting your data will be wasted if the data are lost. Data should always be stored in 3 locations:

  1. Your computer
  2. The 'cloud'
  3. An external hard drive that is hidden somewhere far away from your computer
  
Not all files are of equal value. Set a folder on your computer that you can sync with an online service like **OneDrive**, **Dropbox**, or **Google Drive**. Set up auto-sync with the folder so that you don't have to worry about manually backing up the files to the cloud -- just the external hard drive.

If you are working with large datasets like high-throughput sequence data, it should be stored on the CAC servers AND at least one external hard-drive (paid from grant money) until it can be archived to NCBI for publication. 

## Meetings

Don't underestimate the value of meetings -- with your committee, with your adviser, with your lab group. Schedule time to **prepare** for your meetings. Some things to consider:
  
  * Summarize accomplishments since the last meeting
  * Outline of work plan for the next meeting
  * A list of problems you encountered and what you did to address them
  * Anything you need from the committee or adviser to move forward

## Useful Habits

There are a number of habits you can try. Here are some suggestions from past discussions with students. Not everything will work with your own personality and preferences. Try different options and see what works for you.  

If you have trouble focusing: 

  * Try moving to a new space for specific goals of reading, writing, coding, etc. (e.g. library, office, café, empty classroom)
  * Try the Pomodoro method -- a set time of focused work (e.g. 25 minutes) followed by a short break (e.g. 5 minutes). Repeat. 
  * Schedule dedicated reading and writing time, and stick to it!. 
  * Set a reward system
  * Avoid distraction! This one seems to be universal. Mute your phone notifications, email, avoid social media, news websites, etc. Set aside specific times of the day to do this.
  * Take a break, like a real break! Maybe you are just mentally exhausted.
  * Take ~ 30 minutes in the morning to organize and visualize all of your activities for the day
  * Rethink your work and life schedule in terms of energy management, not just time management. For example, if certain activities energize you, put them at the beginning of the day, and put energy-draining activities at the end of the day. 
  * Make a physical to-do list and take satisfaction in crossing things off (including 'make to-do list')
  * Start with a short, easy task to get things moving

## Some useful tools & tricks

### CODING

  * Use self-contained folders, e.g. R project folders. Include folders for data, output, and other organizing files. Include a README.md or .Rmd to keep careful notes about your data (e.g. variable names) and analyses (e.g. specific pipeline steps, code)

### WRITING

  * Pen & Paper 
  * Microsoft Word
  * Stickies (real & virtual)
  * Text Edit
  * Overleaf
  * R Markdown/Bookdown
  * Rocketbooks: Pen & Paper + app to save writing
  * Remarkable (markable tablet with e-ink; ~$600?); cheaper versions plug into your computer USB to ‘screen mirror’ and capture notes
  * Notion (online note taking app with some scrapbooking elements)








