---
title: "Colautti Lab Manifest <br> > Presentations"
output: html_document
---

# WARNING!

  1. __Don't underestimate__ how much work it is to put together an effective presentation. Generally, the shorter the presentation, the more editing is required.
  2. __Plan ahead.__ Have everything planned out before you even start
  3. __Less is more.__ Avoid overcrowding. Don't write down phrases or sentences that you are going to say anyway.

This [Colautti Lab Powerpoint Template](../Files/ColauttiLab_SlideFormat.pptx) includes pre-formatted slides featuring lab colours. Use this rather than the garbage and over-used templates that Microsoft provides.

# Figures

Read and summarize [Ten Simple Rules for Better Figures](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003833)


# Graphic design

Graphical elements and concepts are the basis slide or poster design. Here are a few basics:

1. **Lines** -- this includes text
2. **Shapes** -- any 2-dimensional shape
3. **Forms** -- modify 2-d shapes use shading and perspective to imply 3-dimensional shapes
4. **Texture** -- adds feel to shapes and forms
5. **Balance** -- describes how objects are laid out
6. **Rule of thirds** -- create a 3x3 grid on the page and have major elements fall along these lines rather than smack in the middle of the page or some other random place.

Watch this short (~5 min) [Youtube video on design fundamentals](https://www.youtube.com/watch?v=YqQx75OPRa0)

Graphic design is the unsung hero of visual presentation, both in slides and posters. There are entire degrees devoted to this stuff, but a few simple rules can take you a long way. These fall into a few general categories:

1. **Colour Theory**
2. **Layout and Composition**
3. **Typogaphy**
4. **Images**

## Colour theory

How to choose colours for your slides or poster?

1. Start with a theme -- e.g. colour of your study organism or major photos
2. Use the colour wheel to choose a colour scheme:
    1. **Monochromatic**
    2. **Analogous**
    3. **Complementary**
    4. **Split complementary**
    5. **Triadic**
3. Modify Hue, Saturation and Value

Or use a website to help you define a palette:

* [Adobe's colour wheel tool](https://color.adobe.com/create/color-wheel/)
* [coolors.co](https://coolors.co/)
* [colormind.io](http://colormind.io/)
* [paletton.com](http://paletton.com/#uid=1000u0kllllaFw0g0qFqFg0w0aF)

Watch the [Youtube Video on Colour Theory](https://www.youtube.com/watch?annotation_id=annotation_3938340727&feature=iv&src_vid=a5KYlHNKQB8&v=_2LLXnUdUIc)

## Layout and composition

There are 5 basic principles of good composition:

1. **Proximity** -- group similar/related elements together and different/unrelated elements apart
2. **Negative space** -- think of empty space as important as text or images. Use space to separate and define sections. If you don't have empty space then your composition will look cluttered.
3. **Alignment** -- use a grid system and take the extra time to align graphics and text to the grid. Misaligned elements look sloppy.
4. **Contrast** -- Use different colours, sizes, text styles, to emphasize elements and direct the reader.
5. **Repetition** -- Choose a limited number of elements and use them consistently (e.g. repeat the same colour for all section headers rather than different colours for each).

These are explained in more detail in this short (5 min) introductory [YouTube Video on Composition and Layout](https://www.youtube.com/watch?v=a5KYlHNKQB8)

## Typography

Choice of text is as important as any other element of your slide or poster presentation. There are three main text types, but in most cases you want to stick with a **sans serif** font throughout your presentation or poster.

1. **Serif** -- (e.g. Times New Roman) These fonts have embellishments  that look nice but
2. **Sans Serif** -- (e.g. Arial) These fonts are simpler but easier to read at a distance.
3. **Display fonts** -- (e.g. ALL CAPS, comic sans) These fonts should be used sparingly.

It's usually best to use 1 font type, and then use bold, italic and size to create variants for different headers and body text.

Typography has several design elements that are analogous to the considerations for general layout and composition, as outlined above. 

1. **Hierarchy** -- Use hierarchy of text (e.g. header, subheader, reference)
2. **Leading** -- Line spacing
3. **Tracking** -- Letter spacing
4. **Kerning** -- space between individual letters

See the [Youtube Video on Typography](https://www.youtube.com/watch?v=sByzHoiYFX0)

## Images

Images are absolutely crucial to any good presentation or poster. Take lots of pictures while working on your project and organize them so that you can quickly find them when putting together slides or a poster.

Understand the difference between *vector* and *raster* graphics. Search online or look at the first few slides of this lecture from BIOL 812: [Visualizations: Examples and key concepts](../Lectures/Graphical_Concepts.pdf)

Be sure to use high-quality, high-resolution photos for posters -- you need to zoom way in to see if your image will look pixelated when printed. Don't distort images by expanding along the x- or y-axis without adjusting the other axis by the same proportion.

With very few exceptions, you should use vector images for most graphs. Some exceptions can be made if your graph contains a raster image (e.g. map) or if you have too many data points (>>100,000). You can use the svg() function in R to output to an open-source vector format with the .svg extension.


See the [Youtube Video on Images](https://www.youtube.com/watch?v=MELKuexR3sQ)

# Other Tips

Read the tips and guidelines for presentations from the [TED Blog](http://blog.ted.com/10-tips-for-better-slide-decks/?utm_campaign=social&utm_medium=referral&utm_source=facebook.com&utm_content=ted-blog&utm_term=business).

See also: [Powerpoint Graphics Tips](https://www.slideshare.net/PlantTeaching/images-for-impact?ref=https://www.botany.one/2016/08/a-picture-is-worth-a-thousand-bullet-points/)

Check out this very different and innovative idea about poster design in this [Youtube Video](https://www.youtube.com/watch?v=1RwJbhkCA58). 

